language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4

before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then 2to3 -n -w --no-diffs ec2ansible tests; fi

script:
  - python setup.py test
